### ISSUE TITLE
horizontal scroll

### ISSUE THREAD

**Issue by Dyl777** [bachvtuan/Github-Contribution-Graph#10]
Am trying to use the contribution graph to be responsive, so for smaller screens, I want to use a horizontal scroll on it however I have tried giving either <svg width="auto" height="110" viewBox="0 0 auto 110" font-size="13" class="js-calendar-graph-svg">' or <g transform="translate(20, 20)" class=""> in line 175 in github_contribution.js the classname horz-scroll and I have even tried wrapping <svg width="auto" height="110" viewBox="0 0 auto 110" font-size="13" class="js-calendar-graph-svg">' in a div and giving the div classname horz-scroll which is defined as 
.horz-scroll{
    overflow-x: scroll;
    overflow-y: hidden;
    -webkit-overflow-scrolling: touch;
}
but all these don't work. How could you do this??

**Comment by bachvtuan** [comment]
![image](https://github.com/bachvtuan/Github-Contribution-Graph/assets/2065400/a0e26f93-5067-4876-97ab-00d79559f55e)
Just try at the demo site:
Add this style to  ` overflow: auto;`  to `#github_chart_1` and it is scrollable on the horizontal side.

**Comment by Dyl777** [comment]
Doesn't seem to work. When I visit your hosted version, yours works fine but mine doesn't. I have tried changing my jquery version to match yours, still doesn't work. Could you send me the source code of the hosted one let me give a shot
![CaptureHTML](https://github.com/bachvtuan/Github-Contribution-Graph/assets/117218643/c8da1f2c-7f79-4675-a261-f42e7ebd52ee)

**Comment by Dyl777** [comment]
The scroll sides only appear when use overflow:scroll and it just shows the white scroll with no movable bar

**Comment by Dyl777** [comment]
OK.IT SEEMS LIKE I SOLVE THE PROBLEM, IT WAS A PROBLEM WITH THE //Fixed size for now with width= 721 and height = 110
          var wire_html = 
            '<svg width="720" height="110" viewBox="0 0 720 110" font-size="13" class="js-calendar-graph-svg">'+
              '<g transform="translate(20, 20)">'+
                loop_html +
              '</g>'+
            '</svg>'; WHERE WIDTH WAS INITIALLY AUTO.

THANKS FOR YOU HELP
