### ISSUE TITLE
Add viewBox attribute to svg

### ISSUE THREAD

**Issue by thomas-price** [bachvtuan/Github-Contribution-Graph#3]
You may wish to add a `viewBox` attribute to svg. 
The benefit is it allows greater control over svg resizing when using css.
```
 '<svg width="721" height="110" viewBox="0 0 721 110" class="js-calendar-graph-svg">'+
```
Example:

- css `width: 100%;` without `viewBox` will chop the svg display to fit
- css `width: 100%;` with `viewBox` will resize the whole svg display to fit

**Comment by bachvtuan** [comment]
I updated.

**Comment by thomas-price** [comment]
Thank you
