### ISSUE TITLE
JS error when future calendar contains no data

### ISSUE THREAD

**Issue by thomas-price** [bachvtuan/Github-Contribution-Graph#4]
Our application allows users to view a calendar in the future (and it possibly may contain no data).
Note:  start_date > current_date

This resulted in a JS error:
```
github_contribution.js?ver=4.3.3:141 Uncaught TypeError: Cannot read property 'x' of undefined
    at start (github_contribution.js?ver=4.3.3:141)
    at n.fn.init.$.fn.github_graph (github_contribution.js?ver=4.3.3:222)
    at my-custom.js?ver=4.3.3:4619
```

To resolve this we commented out this code:
```
              /*if ( start_date > current_date ){
                //Break the loop
                break;
              }*/
```
Is this a use case you wish covered by your code?

**Comment by bachvtuan** [comment]
I don't get the issue. Can you post full code ?

**Comment by thomas-price** [comment]
Hi Tuan,
Nice solution.
Our Use Case is:
1. Create a Calendar that is in the future (start_date > current_date)
2. May create an empty data: list

When this Use Case occurs, the result is a JS error (as above)

If we comment out the code (as above), the result is correct (see attached image)
![image](https://user-images.githubusercontent.com/66541936/97662206-76931a00-1aca-11eb-85f1-27b0f690f6fe.png)

**Comment by bachvtuan** [comment]
I updated code to support start_date too. 
You can read README.md  or visit demo http://bachvtuan.github.io/Github-Contribution-Graph/

**Comment by thomas-price** [comment]
Hi Tuan,
Thank you.
There is a small typo in `readme.md`
```
line 31: 365 days not 635 days
```
I will test the other changes over the next few days

regards
Thomas

**Comment by thomas-price** [comment]
Testing was successful
Many thanks

regards
Thomas
