### ISSUE TITLE
How to set the value?

### ISSUE THREAD

**Issue by heidarymr** [bachvtuan/Github-Contribution-Graph#6]
I did not understand what the date-value array structure should look like. It looks like it should be as follows, but the getRandomTimeStamps function only generates the timestamp. How to set the value?

`data= [ {date: '1575977575868', value:'7'},{date: '1592821975868', value:'0'},... ];
`
or 
`data= [ {'1575977575868', '7'},{ '1592821975868','0'}, ... ];
`

**Comment by bachvtuan** [comment]
You can try function "getRandomTimeStamps"  on demo link http://bachvtuan.github.io/Github-Contribution-Graph/.

![Screenshot_2020-11-02_18-46-49](https://user-images.githubusercontent.com/2065400/97864823-cc222d80-1d3b-11eb-892d-8bb02450d476.png)


You just need push all timestamps to array and plugin will group them by date.

if you want display 3 events happened on single date . Simply just append 3 duplicated timestamp items  for examples 
```
data = [1604317761305, 1604317761305, 1604317761305]
```

**Comment by birazoutcode** [comment]
I am getting an error. Github graph is not a function. Here is my code


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="~/js/github_contribution.js"></script>
<link href="~/css/github_contribution_graph.css" rel="stylesheet" />

<div id="myGraph"></div>

<script>
    $(document).ready(function () {
        $('#myGraph').github_graph({
            // start from 2022, null is default
            start_date: new Date(2022, 00, 00, 0, 0, 0),
            data : [1604317761305, 1604317761305, 1604317761305],
            // single text and plural text
            texts: ['category', 'categories'],
            //Override month names
            month_names: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T11', 'T12'],
            //Override horizontal day name
            h_days: ['2', '4', '6'],
            //override colours
            colors: ['gray', 'purple', 'yellow', 'green', 'red']
        });
    });
</script>

**Comment by touatily** [comment]
It would be interesting to change the format of data to something like : `[{"timestamp": XXXXXXXX, "nb_events": 2}, ...]`

**Comment by bachvtuan** [comment]
Hi @touatily, also supported below data:
```
var list_of_timestamp = [
  {
    timestamp: 1624865396654,
    count: 2
  },
  {
    timestamp: 1624865396655,
    count: 5
  }
];
```
